### PR TITLE
Updated grpc and google_protos deps.

### PR DESCRIPTION
**Pull request by wtcross**
The minor version of both grpc and google_protos have been bumped by one.
The client library was also regenerated using the buf cli.

The only file outside of generated code that was changed is mix.exs.

### CODE REVIEW

**Comment by wtcross** [comment]
I ran a local SpiceDB instance and verified that all tests are passing.

**Comment by wtcross** [comment]
By the way, I'm very excited to start using SpiceDB with a large Elixir project. I am very grateful that you have created and are maintaining this library. I'll help out where I can once I really start digging into SpiceDB.

**Comment by wtcross** [comment]
I just realized I forgot to update the version. I'll wait for feedback before doing that.

**Comment by goodhamgupta** [comment]
Hi @wtcross. Thank you for taking the time to improve this repo!

All your changes look good! Like you suggested, we can now add a version bump, and then I can merge the changes in!

**Comment by zagraves** [comment]
Hi @goodhamgupta. I'd love to start using a new version of authzed_ex with these changes made 🙏

**Comment by goodhamgupta** [comment]
Hi @zagraves and @wtcross, I've published the new version(0.0.6) to Hex today, and it's available here: https://hex.pm/packages/authzed/0.0.6

Apologies for the late response. I wasn't sure if the package version bump had been made since there was no activity on this PR. There were minor CI and formatting issues, so I forked this PR here: https://github.com/goodhamgupta/authzed_ex/pull/18, and deployed this fork instead.

Thanks for your work @wtcross, and for your patience! 😄

**Pull request closed without merging**
